services:
  api:
    build: .
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always
    networks:
      - projeto-network

networks:
  projeto-network:
    external: true
